name = "curatoros-errors"
main = "src/entry-v1.18.js"
compatibility_date = "2026-08-09"
compatibility_flags = ["global_fetch_strictly_public"]
workers_dev = true

[[kv_namespaces]]
binding = "CURATOR_ERROR_RECORDS"
id = "447306da3a754b44830d2ac8608322c0"

[triggers]
crons = ["* * * * *", "47 * * * *"]

[observability]
enabled = true
