name = "error"
main = "src/entry-v1.27.js"
compatibility_date = "2026-08-09"
compatibility_flags = ["global_fetch_strictly_public"]
workers_dev = true

[build]
command = "node scripts/write-build-meta.mjs"

[[kv_namespaces]]
binding = "CURATOR_ERROR_RECORDS"
id = "447306da3a754b44830d2ac8608322c0"

[version_metadata]
binding = "CF_VERSION_METADATA"

[triggers]
crons = ["* * * * *", "47 * * * *"]

[observability]
enabled = true
